newspaper_app/urls.py
from django.urls import path
from .views import chooseToEdit, mainView, createNew, chooseToDelete, deleteOne, editing

urlpatterns = [
    path('', mainView, name="main"),
    path('create', createNew, name="create"),
    path('edit', createNew, name="create"),
    path('delete', chooseToDelete, name="choose_delete"),
    path('edit_choose', chooseToEdit, name="choose_edit"),
    path('editing/<int:id>', editing, name='editing'),
    path('delete/<int:id>', deleteOne, name="delete")
]

newspaper_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newspaper_app.urls')),
]

newspaper_app/models.py
from django.db import models

import manage

# Create your models here.
class newspaper_db(models.Model):
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    author = models.CharField(max_length=255)

    class Meta:
        db_table = 'newspaper_obj'
        managed = False 
        #this is to not manipulate the existing table

newspaper_app/forms.py
from django import forms
from .models import newspaper_db

class newNewspaper_form(forms.ModelForm):
    class Meta:
        model = newspaper_db
        fields = ['title', 'description', 'author']

newspaper_app/views.py
from django.contrib import auth
from django.shortcuts import get_object_or_404, redirect, render
from .models import newspaper_db
from .forms import newNewspaper_form  

# Create your views here.
def mainView(request):
    info = newspaper_db.objects.all()
    return render(request, 'main.html', {'news': info})

def createNew(request):
    if request.method == 'POST':
        form = newNewspaper_form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('main')

    else:
        form = newNewspaper_form()

    return render(request, 'create.html',  {'form': form})

def deleteOne(request, id):
    newspaper = get_object_or_404(newspaper_db, id=id)

    if request.method == 'POST':
        newspaper.delete()
        return redirect('main')


def chooseToDelete(request):
    info = newspaper_db.objects.all()
    return render(request, 'delete.html', {'news': info})

def chooseToEdit(request):
    info = newspaper_db.objects.all()
    return render(request, 'edit.html', {'news': info})


def editing(request, id):
    newspaper = get_object_or_404(newspaper_db, id=id)
    form = newNewspaper_form(instance=newspaper)

    if request.method == 'POST':
        form = newNewspaper_form(request.POST, instance=newspaper)
        if form.is_valid():
            form.save()
            return redirect('main')  # Redirect after successful save
        else:
            print(form.errors)  # Print errors to console for debugging

    return render(request, 'editing.html', {'form': form, 'id': id})

templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/create.css' %}">
</head>
<body>
<form action="{% url 'create' %}" method="post">
	{% csrf_token %} 
<h3>Create a New Item</h3>


    <div class="input">
        <label for="id_title">Title</label>
        {{ form.title }}
    </div>
    <div class="input">
        <label for="id_description">Description</label>
        {{ form.description }}
    </div>
    <div class="input">
        <label for="id_author">Author</label>
        {{ form.author }}
    </div>

<button type="submit" style="color: black;"> Send </button>

</form>
</body>
</html>

templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
Which one will you delete?
	{% for item in news %}
	
	<form action="{% url 'delete' item.id %} " method="post">
			{% csrf_token %}
		<button type="submit" class="item">
			
				{{ item.title }}
			
		</button>	
	</form>

			{% endfor %}
</body>
</html>

templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
Which one will you edit?
	{% for item in news %}
<br>	
	<a href="{% url 'editing' item.id %}">{{ item.title }}</a>
	{% endfor %}
</body>
</html>

templates/editing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Item</title>
</head>
<body>
<form action="{% url 'editing' id %}" method="post">
        {% csrf_token %}
        <h3>Edit Item</h3>

        <div class="input">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
         <div class="input">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
	<div class="input">
            <label for="id_athor">author</label>
            {{ form.author }}
        </div>
        <button type="submit">Updatew</button>
    </form>
</body>
</html>

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
<style>
*, *::after, *::before{
	padding: 0;
	margin: 0;
	box-sizing: border-box;
}
			.btn_opt{
padding: 1.2em;
border-radius: 2em;
background-color: #fee;
min-width: 100%;
			}

.item{
		padding: 3em;
			background-color: #eab;
			border-radius: 18px;
			border: 1px black solid;
			
			}
</style>

</head>
<body>
	<div id="mainTitle" style="margin: 0 auto; border: 2px black solid; padding: 1em; border-radius: 18px; width: 10em;text-align: center ;margin-top: 1em;">
<h5>TEST CRUD</h5>	
	</div>

	
	<div id="container" style="display: flex; justify-content: space-around; align-items: center;">

		<div id="buttons_box" style="display: flex; flex-direction: column; justify-content: space-around; align-items: center; gap: 1em;">
			<a class="btn_opt" href="{% url "create" %}">create</a>
		<a href="{% url "choose_delete" %}" class="btn_opt">delete</a>
		<a href="{% url "choose_edit" %}" class="btn_opt">edit</a>
		</div>
		
		<div id="info_box">
			the news are: <br> 
			{% for item in news %}
			<div class="item">
			{{item.title}}

			<h5 style="margin: 15px 0;">{{item.description}}</h5>
			</div>	
			
			{% endfor %}
		</div>

	</div>
</body>
</html>